- name: Play EOS
  hosts: localhost
  collections:
    - kubernetes.core
  vars:
    namespace_prefix: eos
    namespaces_number: 5
    max_instances: 2
    app_name: eos-app
  tasks:
  - name: Install pre-requisites
    pip:
      name:
      - pyyaml
      - kubernetes

  - name: Set variables
    set_fact:
      pods_and_ns_filename: "pods_and_namespaces.txt"
      image: "nginx"

  - name: Create pod-namespace file
    shell: touch {{ pods_and_ns_filename }}
    
  - name: Get absolute path
    shell: pwd
    register: path

  - name: Get filepath
    set_fact:
      filepath: "{{ path.stdout }}/{{ pods_and_ns_filename }}"

  - name: Set max_instances
    set_fact:
      max_instances: "{{ max_instances if max_instances is defined  else namespaces_number}}"

  - name: Deploy role
    include_role:
      name: deploy
    vars:
      filename: "{{ filepath }}"
      namespace_name: "{{ namespace_prefix + '-%x' | format(item) }}"
      replicas: "{{ (item | int <= max_instances | int ) | ternary(item, max_instances) }}"
    loop: "{{ range(1,  namespaces_number + 1)|list }}"
 