- name: Play EOS
  hosts: localhost
  collections:
    - kubernetes.core
  vars:
    namespace_prefix: eos
    namespaces_number: 5
    #max_instances: 2 #Use to limit the number of replicas
    app_name: eos-app
    pods_and_ns_filename: "pods_and_namespaces.txt"
    image: "nginx"
  tasks:
  - name: Install pre-requisites
    pip:
      name:
      - pyyaml
      - kubernetes

  - name: Get absolute path
    shell: pwd
    register: path
    
  - name: Set variables
    set_fact:
      max_instances: "{{ max_instances if max_instances is defined  else namespaces_number}}"
      filepath: "{{ path.stdout }}/{{ pods_and_ns_filename }}"

  - name: Touch the same file, but add/remove some permissions
    ansible.builtin.file:
      path: "{{ filepath }}"
      state: touch

  - name: Deploy role
    include_role:
      name: deploy
    vars:
      filename: "{{ filepath }}"
      namespace_name: "{{ namespace_prefix + '-%x' | format(item) }}"
      replicas: "{{ (item | int <= max_instances | int ) | ternary(item, max_instances) }}"
    loop: "{{ range(1,  namespaces_number + 1)|list }}"
 
